const data = {
  "banner": {
    "title": '智慧变电站综合运维管理平台',
    "intra": '设备的精益管理、精益检测和精益管控，增强供电保障服务保障能力',
  },
  "intra": {
    "width": "w65",
    "text": "压测宝通过全球分布式网络发起真实压力，\\n帮助企业评估应用性能容量，发现应用全链路性能瓶颈，\\n从而保障产品迭代交付适应企业业务的高速增长。"
  },
  "modules": [{
    "name": "itemsB",
    "title": "应用场景",
    "intra": "涵盖变电站智能运维与保电等8大场景，减少重复性、低附加值的繁琐工作，让运维人员更加专注于故障抢修、运行分析、指挥决策等高附加值工作，减少故障停电时间，保障电网稳定供电、安全运行",
    "moduleClass": "itemsB-vertical",
    "picSize": "l",
    "items": [{
      "pic": "image/product/icon-b71.png",
      "title": "数据采集与融合",
      "text": "基于无人机、机器人和传感器等多种监测手段，对开关柜、变压器等一次设备全生命周期的数十万测点数据进行采集汇聚"
    }, {
      "pic": "image/product/icon-b72.png",
      "title": "设备全态信息感知",
      "text": "通过3D全景实时展示一次设备四遥数据，让变电站运维人员及时掌握设备运行情况，对设备常见的温度异常、局部放电异常等数百种故障进行及时处理"
    }, {
      "pic": "image/product/icon-b73.png",
      "title": "设备状态分类评估",
      "text": "建立设备指标评价体系，对不同类型设备建立状态评估模型，可实时在线展示设备运行状态、对设备进行定期自动体检，为设备检修提供决策依据"
    }, {
      "pic": "image/product/icon-b74.png",
      "title": "设备故障智能预警",
      "text": "基于设备缺陷报告、检修记录、运行工况等历史数据，建立开关柜局部放电异常、变压器温度异常等故障预测模型，采用人工智能算法，反映故障发生规律，实现对故障的精准预测"
    }, {
      "pic": "image/product/icon-b75.png",
      "title": "设备故障智能分析",
      "text": "通过知识图谱、神经网络等技术，实现对设备故障的智能分析。当变电站设备发生故障或状态异常时，系统根据当前故障特征进行自动推理，并自动推荐解决方案和相似缺陷的报告案例"
    }, {
      "pic": "image/product/icon-b76.png",
      "title": "保电-保电状态综合管控",
      "text": "通过3D全景实时展示保电区域内设备运行状态，对于已经发生的故障系统自动判断故障停电范围和停电时长，实时跟踪保电人员地理位置"
    }, {
      "pic": "image/product/icon-b77.png",
      "title": "保电-故障抢修",
      "text": "保电区域一旦发生故障，系统立即自动向设备所属管辖范围的保电单位下发工单，如果抢修人员未及时对工单进行确认，系统会通过智能外呼自动拨打抢修人员电话进行提醒"
    }, {
      "pic": "image/product/icon-b78.png",
      "title": "保电-故障抢修全程跟踪",
      "text": "系统对工单处理进度、故障抢修过程、故障抢修结果、备品备件运送过程进行全程跟踪，对抢修复盘和决策提供依据"
    }]
  }, {
    "name": "only-text",
    "moduleClass": "w78 bg-blue",
    "text": "智慧变电站综合运维管理平台包括物理世界感知层、数据接口层、通讯网络层、数据与智能服务层以及应用系统层，整体系统架构图下图所示："
  }, {
    "name": "only-pics",
    "moduleClass": "",
    "pics": [{url: "image/product/isop/pic.jpg"}]
  }, {
    "name": "itemsB",
    "title": "产品优势",
    "wrapClass": "bg-blue",
    "moduleClass": "itemsB-tc itemsB-cols3-l service",
    "items": [{
      "pic": "image/product/icon-b61.png",
      "title": "安全智防御",
      "text": "通过智能感知、智慧诊断、检修策略实现主动防御，减少现场作业频度，提升本质安全"
    }, {
      "pic": "image/product/icon-b62.png",
      "title": "设备智管控",
      "text": "服务规划、设计、基建、生产、营销等全业务流程，真正实现设备寿命周期管理"
    }, {
      "pic": "image/product/icon-b63.png",
      "title": "检修智预测",
      "text": "由“防御性维护”转向“预测性维护”，降低变电站检修成本"
    }, {
      "pic": "image/product/icon-b64.png",
      "title": "资产智增益",
      "text": "最大化延长设备寿命，同型号设备可覆盖变电站，实现可复制、可推广的数字资产变现模式"
    }, {
      "pic": "image/product/icon-b65.png",
      "title": "产业智优化",
      "text": "为产业集团提供技术咨询支持，实现数字孪生交付，促进中国智能制造迈向更高水平"
    }, {
      "pic": "image/product/icon-b66.png",
      "title": "服务智定制",
      "text": "通过“设备画像”为政府、企业提供设备运维咨询服务，设备购置咨询服务、数字孪生定制服务"
    }]
  }, {
    "name": "itemsI",
    "title": "产品案例",
    "intra": "智能变电站综合运维管理平台已在上海浦东供电公司、江苏电科院下辖的多个变电站实施落地，帮助用户全力加快基于电力物联网的数字化变电站建设，推动安全生产数字化转型，实现精准作业，探索未来变电站及运维模式变革",
    "wrapClass": "swiper",
    "items": [{
      "pic": "image/product/isop/pic-01.jpg",
      "text": "基于GIS地图，对辖区变电站地理位置、基本属性信息、设备运行状态、关键指标以及告警事件实时展示"
    }, {
      "pic": "image/product/isop/pic-02.jpg",
      "text": "变电站基本属性信息、设备运行状态、关键指标以及告警事件实时展示"
    }, {
      "pic": "image/product/isop/pic-03.jpg",
      "text": "通过智能告警规则设置，实时采集设备告警信号，按告警类型分类统计，实现设备告警的宏观管控和统一管理"
    }, {
      "pic": "image/product/isop/pic-14.jpg",
      "text": "可以添加各变电站及其所有设备的指标信息，可以通过指标对变电站设备状态进行评估、设置指标规则"
    }, {
      "pic": "image/product/isop/pic-15.jpg",
      "text": "采集变电站设备全量信息，实时动态感知设备运行状态变化，多源数据融合，汇聚全设备全生命周期数据"
    }, {
      "pic": "image/product/isop/pic-16.jpg",
      "text": "智能告警模块支持告警规则的定义，并对所产生的告警事件进行统一管理，展示告警事件列表以及告警详情"
    }, {
      "pic": "image/product/isop/pic-17.jpg",
      "text": "以报表的形式多维度展示变电站、设备的业务关键指标数据，从各个维度挖掘变电站数据的价值"
    }, {
      "pic": "image/product/isop/pic-18.jpg",
      "text": "可以将各个变电站的间隔、一次设备、二次设备/监测单元及信息添加到系统中，进行管理"
    }, {
      "pic": "image/product/isop/pic-19.jpg",
      "text": "可以将用户辖区的变电站和相关的属性信息，逐一添加到系统中，进行管理"
    }]
  }, {
    "name": "itemsI",
    "title": "产品核心功能",
    "intra": "智能变电站综合运维管理平台已在上海浦东供电公司、江苏电科院下辖的多个变电站实施落地，帮助用户全力加快基于电力物联网的数字化变电站建设，推动安全生产数字化转型，实现精准作业，探索未来变电站及运维模式变革",
    "wrapClass": "bg-blue",
    "moduleClass": "itemsI",
    "items": [{
      "pic": "image/product/isop/pic-11.jpg",
      "title": "辖区变电站概览",
      "text": "基于GIS地图，对辖区变电站地理位置、基本属性信息、设备运行状态、关键指标以及告警事件实时展示"
    }, {
      "pic": "image/product/isop/pic-12.jpg",
      "title": "变电站概览",
      "text": "变电站基本属性信息、设备运行状态、关键指标以及告警事件实时展示"
    }, {
      "pic": "image/product/isop/pic-13.jpg",
      "title": "告警信息统计",
      "text": "通过智能告警规则设置，实时采集设备告警信号，按告警类型分类统计，实现设备告警的宏观管控和统一管理"
    }, {
      "pic": "image/product/isop/pic-14.jpg",
      "title": "指标管理",
      "text": "可以添加各变电站及其所有设备的指标信息，可以通过指标对变电站设备状态进行评估、设置指标规则"
    }, {
      "pic": "image/product/isop/pic-15.jpg",
      "title": "全局信息感知",
      "text": "采集变电站设备全量信息，实时动态感知设备运行状态变化，多源数据融合，汇聚全设备全生命周期数据"
    }, {
      "pic": "image/product/isop/pic-16.jpg",
      "title": "智能告警",
      "text": "智能告警模块支持告警规则的定义，并对所产生的告警事件进行统一管理，展示告警事件列表以及告警详情"
    }, {
      "pic": "image/product/isop/pic-17.jpg",
      "title": "报告报表",
      "text": "以报表的形式多维度展示变电站、设备的业务关键指标数据，从各个维度挖掘变电站数据的价值"
    }, {
      "pic": "image/product/isop/pic-18.jpg",
      "title": "设备管理",
      "text": "可以将各个变电站的间隔、一次设备、二次设备/监测单元及信息添加到系统中，进行管理"
    }, {
      "pic": "image/product/isop/pic-19.jpg",
      "title": "变电站管理",
      "text": "可以将用户辖区的变电站和相关的属性信息，逐一添加到系统中，进行管理"
    }]
  }, {
    "name": "consulting",
    "text": "只需30秒，立即体验变电站智慧运维服务",
    "url": ""
  }]
}

export default data